"""Generating the wheel being labelled, in the background, and saying so (D-123).

Split from :mod:`avialsync.ui.controllers.wheel_controller`. Every click
re-projects the clicked ends at once (well under a millisecond) and asks for
the wheel to be generated by :class:`~avialsync.engine.wheel_fit_worker.WheelFitWorker`,
a registered job (rules 3 and 11): one at a time, and a click made while one
runs is fitted when it returns, so the answer always matches the latest clicks.
The notification strip says when the wheel is first generated and when its
fit turns poor -- once per change, not per click.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from PySide6.QtCore import QThread

from avialsync.core.wheel import fit_issue
from avialsync.core.wheel_fit import LabelledFit
from avialsync.engine.wheel_fit_worker import WheelFitWorker
from avialsync.ui.controllers import wheel_display as display
from avialsync.ui.controllers.wheel_placement import (
    Placement,
    describe_adjustment,
    estimate_missing,
)
from avialsync.ui.i18n import tr
from avialsync.ui.job_manager import on_ui_thread

if TYPE_CHECKING:
    from avialsync.ui.main_window import MainWindow

__all__ = ["refit"]


def refit(window: MainWindow) -> None:
    """Re-project at once, and generate the wheel in the background (rule 3, D-123)."""
    placement = window._wheel_placement
    if placement is not None:
        estimate_missing(placement, display.camera_models(window))
        placement.generation += 1
        if not placement.fitting:
            _start_fit(window, placement)
    display.refresh(window)


def _start_fit(window: MainWindow, placement: Placement) -> None:
    """One fit job at a time; a click during it is fitted when it returns."""
    placement.fitting = True
    generation = placement.generation
    worker = WheelFitWorker(
        placement.spec, placement.ordered(), display.camera_models(window), placement.flipped
    )

    def done(labelled: LabelledFit | None, problem: str = "") -> None:
        if window._wheel_placement is not placement:
            return
        placement.fitting = False
        if generation != placement.generation:
            _start_fit(window, placement)
            return
        if labelled is None:
            placement.fit, placement.note, placement.problem = None, "", problem
        else:
            placement.fit, placement.problem = labelled.fit, ""
            placement.note = describe_adjustment(placement.spec, labelled)
        _announce_preview(window, placement)
        display.refresh(window)

    def wire(thread: QThread) -> None:
        worker.finished.connect(on_ui_thread(done, window))
        worker.error.connect(on_ui_thread(lambda message: done(None, message), window))
        worker.finished.connect(thread.quit)
        worker.error.connect(thread.quit)

    window._run_job(
        worker,
        label=tr("Generating wheel {name}").format(name=placement.spec.name),
        configure=wire,
    )


def _announce_preview(window: MainWindow, placement: Placement) -> None:
    """Say when the wheel is generated, and when it stops being drawn.

    The fit runs after every click in ~10-20 ms, so there is no job to show
    progress for (rule 11); what the user needs is to know it happened.
    """
    if placement.fit is None:
        placement.announced = ""
        return
    state = "poor" if fit_issue(placement.fit, placement.ordered()) else "shown"
    if state == placement.announced:
        return
    placement.announced = state
    if state == "shown":
        window.notifications.show_success(
            tr(
                "Wheel generated from {bars} bars and drawn dashed in every camera. Check it, "
                "then choose Done Labelling in the Wheels tab."
            ).format(bars=len(placement.fit.indices))
        )
    else:
        window.notifications.show_warning(
            tr(
                "Wheel generated, but it fits your clicks poorly. It is drawn dashed anyway; "
                "the Wheels tab says what to check."
            )
        )
